#!/bin/bash
if [[ $(id -u) != 0 ]]; then
    echo "$0: this command must be run as root!" >&2
    exit 1
fi
function run {
    export LC_ALL=$LANG # needed in container, apparently not set by default
    lxc-create -n ceylon-ci -t debian || return $?
    local builddir=/build
    local builduser=nobody
    function run { lxc-start -n ceylon-ci -- "$@"; } # warning: lxc-execute doesn’t work (requires lxc within container)
    function runin { name=$1; shift; run sudo -u $builduser -- bash -c "export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre; cd $builddir/$name; $*"; } # yes, $*, not $@. Needs to be within the -c argument!
    
    cp {,/var/lib/lxc/ceylon-ci/rootfs}/etc/apt/sources.list &&
    run apt-get update &&
    run apt-get install --yes --no-install-recommends openjdk-7-jdk ant git sudo &&
    run mkdir $builddir &&
    run chown nobody $builddir &&
    run usermod --home $builddir $builduser &&
    runin . git clone --depth=1 https://github.com/ceylon/ceylon-dist.git &&
    runin ceylon-dist sed -i 's\|\<arg\ value=\"clone\"/\>\|\<arg\ value=\"clone\"/\>\ \<arg\ value=\"--depth=1\"/\>\|' build.xml # add --depth=1 option to git; needs nasty quoting
    runin ceylon-dist ant setup &&
    runin ceylon-dist ant publish-all &&
    runin . git clone --depth=1 https://github.com/ceylon/ceylon-sdk.git &&
    runin ceylon-sdk ant publish &&
    runin . git clone --depth=1 https://github.com/ceylon/ceylon.formatter.git &&
    runin ceylon.formatter ant test publish &&
    runin . git clone --depth=1 https://github.com/ceylon/ceylon.ast.git &&
    runin ceylon.ast ant test
    
    status=$?
    lxc-destroy -fn ceylon-ci
    return $status
}
if ! (run &> /tmp/report); then # use subshell: don’t exit when run function exits
    sendmail -f bot@lucaswerkmeister.de -F "Ceylon CI Bot" mail@lucaswerkmeister.de << EOF
Subject: [ceylon-ci] $(date -Idate)
Content-Type: multipart/mixed;
 boundary="boundary"

This is a multi-part message in MIME format.
--boundary
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

Hi! The Ceylon build failed.
Here's the last couple of lines of the report:

$(tail /tmp/report)
--boundary
Content-Type: text/plain; charset=UTF-8;
 name="report.txt"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="report.txt"

$(base64 /tmp/report)
--boundary
EOF
fi
